---
- name: Ensure AWS config directory exists
  file:
    state: directory
    dest: "{{ home_dir | default('/home/' + user) }}/.aws/"
    mode: 0700
    owner: '{{ user }}'
    group: '{{ user }}'
  become: true

- name: Ensure profile is configured.
  template:
    src: config.j2
    dest: "{{ home_dir | default('/home/' + user) }}/.aws/config"
    mode: 0600
    owner: '{{ user }}'
    group: '{{ user }}'
  become: true

- name: Ensure credentials are set.
  block:
    - name: Check if credentials are set.
      command:
        cmd: 'aws configure export-credentials --profile {{ profile }}'
      changed_when: false
      become: true
      become_user: '{{ user }}'
      no_log: true
  rescue:
    - name: Create credentials.
      community.aws.iam_access_key:
        user_name: '{{ aws_iam_user }}'
        rotate_keys: true
        profile: '{{ local_profile }}'
      register: credentials
      delegate_to: localhost
      no_log: true

    - name: Set credentials
      template:
        src: credentials.j2
        dest: "{{ home_dir | default('/home/' + user) }}/.aws/credentials"
        mode: 0600
        owner: '{{ user }}'
        group: '{{ user }}'
      become: true
      notify: 'AWS credentials updated'
      no_log: true
