AWSTemplateFormatVersion: 2010-09-09

Description: >
  Creates an IAM user to allow GitHub Dependabot to read view images when running updates.

Resources:
  Dependabot:
    Type: AWS::IAM::User
    Properties:
      Policies:
      - PolicyName: ecr-updater
        PolicyDocument:
          Version: 2012-10-17
          Statement:
            - Effect: Allow
              Action:
                - 'ecr:ListImages'
                - 'ecr:BatchGetImage'
              Resource: !Sub 'arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'
            - Effect: Allow
              Action:
                - 'ecr:GetAuthorizationToken'
              Resource: '*'
