AWSTemplateFormatVersion: 2010-09-09

Outputs:
  EcrAuthPolicy:
    Description: The Arn of the ECR Read only Policy
    Value: !Ref EcrAuth
    Export:
      Name: EcrAuthPolicy
  EcrReadOnlyPolicy:
    Description: The Arn of the ECR Read only Policy
    Value: !Ref EcrReadOnly
    Export:
      Name: EcrReadOnlyPolicy
  EcrPushPolicy:
    Description: The Arn of the ECR Read only Policy
    Value: !Ref EcrPush
    Export:
      Name: EcrPushPolicy

Resources:
  EcrAuth:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:GetAuthorizationToken'
            Resource: '*'

  EcrReadOnly:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:BatchGetImage'
              - 'ecr:GetDownloadUrlForLayer'
            Resource: !Sub 'arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'

  EcrPush:
    Type: AWS::IAM::ManagedPolicy
    DeletionPolicy: Retain
    Properties:
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - 'ecr:BatchCheckLayerAvailability'
              - 'ecr:CompleteLayerUpload'
              - 'ecr:InitiateLayerUpload'
              - 'ecr:PutImage'
              - 'ecr:UploadLayerPart'
            Resource: !Sub 'arn:${AWS::Partition}:ecr:${AWS::Region}:${AWS::AccountId}:repository/*'

