AWSTemplateFormatVersion: "2010-09-09"
Description: >
  Creates an OIDC Provider for GitHub and provides access to roles for GitHub Actions.

Outputs:
  GitHubEcrPushRole:
    Value: !GetAtt GitHubEcrPush.Arn

Resources:
  OIDC:
    Type: AWS::IAM::OIDCProvider
    Properties: 
      ClientIdList: 
        - sts.amazonaws.com
      ThumbprintList: 
        - 6938FD4D98BAB03FAADB97B34396831E3780AEA1
      Url: https://token.actions.githubusercontent.com

  GitHubEcrPush:
    Type: AWS::IAM::Role
    Properties: 
      Description: Allows GitHub Actions to push images to ECR
      ManagedPolicyArns:
        - !ImportValue EcrAuthPolicy
        - !ImportValue EcrPushPolicy
      AssumeRolePolicyDocument: 
        Statement:
        - Effect: Allow
          Action: sts:AssumeRoleWithWebIdentity
          Principal:
            Federated: !Ref OIDC
          Condition:
            StringLike:
              token.actions.githubusercontent.com:sub: repo:discoverygarden/docker-dgi-proto:*
            StringEquals:
              token.actions.githubusercontent.com:aud: sts.amazonaws.com

