apiVersion: v1
kind: Secret
metadata:
  name: crayfish-key
  namespace: {{ .Release.Namespace}}
type: Opaque
data:
  public: {{ .Values.crayfish.public | b64enc }}
  private: {{ .Values.crayfish.private | b64enc }}
