version: 2
registries:
  ecr-docker:
    type: docker-registry
    url: https://231224489621.dkr.ecr.us-east-1.amazonaws.com
    username: ${{secrets.ECR_AWS_ACCESS_KEY_ID}}
    password: ${{secrets.ECR_AWS_SECRET_ACCESS_KEY}}
updates:
  - package-ecosystem: "docker"
    directory: "infra/templates/islandora"
    schedule:
      interval: "daily"
    registries: "*"
    directory: "activemq-alpine"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "alpaca"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "eclipse-temurin"
        versions: [">= 12.0"]
  - package-ecosystem: "docker"
    directory: "crayfish"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "debian"
        versions: [">= 12.0"]
  - package-ecosystem: "docker"
    directory: "solr-alpine"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "tomcat-cantaloupe"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "tomcat"
        versions: [">= 10.0.0"]

