version: 2
updates:
  - package-ecosystem: "docker"
    directory: "activemq-alpine"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "alpaca"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "crayfish"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "solr-alpine"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "tomcat-cantaloupe"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "tomcat"
        versions: [">= 10.0.0"]
