---
- name: Ensure aws cli is intalled
  include_role:
    name: aws_cli
- name: Ensure AWS profile is configured
  include_role:
    name: aws_profile
  vars:
    user: '{{ microk8s_user.name }}'
    home_dir: '{{ microk8s_user.home }}'

- name: Ensure ECR Key rotation script exists
  template:
    src: ecr-rotate-key.sh.j2
    dest: /usr/bin/ecr-rotate-key.sh
    mode: 0755
    owner: root
    group: root
  notify: 'Updated pull secrets'
  become: true
- name: Make sure secret is set
  meta: flush_handlers
- name: Ensure ECR Key is kept up to date
  cron:
    name: 'Manage ECR Key for {{ registry.name }}'
    special_time: daily
    job: /usr/bin/ecr-rotate-key.sh
    user: '{{ microk8s_user.name }}'
  become: true
