---
- name: Ensure encryption config exsits
  template:
    src: k8s-crypto.yml.j2
    dest: '{{ microk8s_user.home }}/k8s-crypto.yml'
    mode: 0660
    owner: '{{ microk8s_user.name }}'
    group: microk8s
  become: true
  notify: 'Secrets encryption updated'
- name: Ensure microk8s uses encryption config
  lineinfile:
    path: /var/snap/microk8s/current/args/kube-apiserver
    regexp: --encryption-provider-config=
    line: '--encryption-provider-config={{ microk8s_user.home }}/k8s-crypto.yml'
  become: true
  notify: 'Secrets encryption updated'
