---
- name: Ensure Registry direcory exists configured
  file:
    path: '/var/snap/microk8s/current/args/certs.d/{{ item.name }}/'
    state: directory
    owner: root
    group: microk8s
    mode: 0770
  loop: '{{ registries }}'
  become: true

- name: Ensure Registries configured
  template:
    src: hosts.toml.j2
    dest: '/var/snap/microk8s/current/args/certs.d/{{ item.name }}/hosts.toml'
    owner: root
    group: microk8s
    mode: 0660
  loop: '{{ registries }}'
  become: true

- name: Ensure aws cli is intalled
  include_tasks: ecr_auth.yml
  when: >
    'type' in registry and registry.type == 'ecr'
  loop: '{{ registries }}'
  loop_control:
    loop_var: registry
