---
- name: Import EPEL GPG Key.
  rpm_key:
    state: present
    key: https://dl.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-8
  become: true
- name: Ensure EPEL is enabled.
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-8.noarch.rpm
    state: present
  become: true
- name: Ensure snap is installed.
  dnf:
    name: snapd
    state: present
  become: true
- name: Ensure snapd is enabled and started.
  service:
    name: snapd
    enabled: true
    state: started
  become: true
- name: Ensure snap symlink in place
  ansible.builtin.file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
  become: true
- name: Ensure Microk8s in installed.
  community.general.snap:
    name: microk8s
    classic: true
    state: present
  become: true
