---
- name: Add groups
  user:
    name: alexander
    groups:
      - microk8s
    append: true
  become: true

- name: Ensure microk8s service user exists
  user:
    name: '{{ microk8s_user.name }}'
    group: microk8s
    home: '{{ microk8s_user.home }}'
    state: present
    shell: /usr/bin/false
    password_lock: true
  become: true
