services:
  activemq:
    image: activemq:5.16.2-alpine
    ports:
    - 61616:61616
    - 61613:61613
    - 1833:1833
    - 5762:5760
    - 8161:8161
  memcached:
    image: memcached:1.6-alpine
    deploy:
      resources:
        limits:
          memory: 256M
    ports:
    - 11211:11211
  drupal-crayfish:
    image: drupal-crayfish:8.x-manage
    network_mode: "host"
    environment:
    - APACHE_RUN_DIR=/var/www/html
    - APACHE_RUN_USER=www-data
    - APACHE_RUN_GROUP=www-data
    - APACHE_PID_FILE=/var/run/apache2/apache2.pid
    - APACHE_RUN_DIR=/var/run/apache2
    - APACHE_LOCK_DIR=/var/lock/apache2
    - APACHE_LOG_DIR=/var/log/apache2
    - LANG=C
    - POSTGRES_HOST=localhost
    - DRUPAL_DB_NAME=drupal
    - DRUPAL_DB_USER=drupal
    - DRUPAL_DB_PASSWORD=/run/secrets/db-password
    volumes:
    - /opt/www/d8_configs/default/:/opt/www/d8_configs/default/
    - /opt/www/drupal/sites/default/provisioned_content/:/opt/www/drupal/sites/default/provisioned_content/
    - /opt/www/drupal/sites/default/i8-specific/:/opt/www/drupal/sites/default/i8-specific/
    - ${PWD}/actual.25-crayfish-homarus.conf:/etc/apache2/conf-available/25-crayfish-homarus.conf
    - ${PWD}/actual.25-crayfish-houdini.conf:/etc/apache2/conf-available/25-crayfish-houdini.conf
    - ${PWD}/actual.25-crayfish-hypercube.conf:/etc/apache2/conf-available/25-crayfish-hypercube.conf
    - ${PWD}/actual.25-80-dgi.conf:/etc/apache2/sites-available/25-80-dgi.conf
    - ${PWD}/actual.settings.php:/opt/www/drupal/sites/default/settings.php
    - ${PWD}/actual.flysystem_config.json:/opt/www/drupal/sites/default/flysystem_config.json
    - ${PWD}/actual.trusted_hosts.json:/opt/www/drupal/sites/default/trusted_hosts.json
    - ${PWD}/actual.islandora_iiif.settings.yml:/opt/www/drupal/sites/default/config_override/islandora_iiif.settings.yml
    - ${PWD}/actual.openseadragon.settings.yml:/opt/www/drupal/sites/default/config_override/openseadragon.settings.yml
    - ${PWD}/actual.search_api.server.default_solr_server.yml:/opt/www/drupal/sites/default/config_override/search_api.server.default_solr_server.yml
  karaf:
    image: karaf:4.2.11-alpine
    ports:
    - 1099:1099
    - 8101:8101
    - 44444:44444
    volumes:
    - ${PWD}/actual.org.fcrepo.camel.service.activemq.cfg:/opt/karaf/etc/org.fcrepo.camel.service.activemq.cfg
    - ${PWD}/actual.crayfish.dgi.xml:/opt/karaf/deploy/crayfish.dgi.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.homarus.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.homarus.blueprint.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.houdini.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.houdini.blueprint.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.hypercube.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.hypercube.blueprint.xml
  solr:
    image: solr:8.9.0-alpine
    ports:
    - 8983:8983
  cantaloupe:
    image: cantaloupe:4.1.9-tomcat
    ports:
    - 8080:8080
    volumes:
    - ${PWD}/actual.info.yaml:/opt/cantaloupe_configs/info.yaml
secrets:
  db-password:
    file: db/password.txt
