---
houdini:
  executable: "/usr/bin/convert"
  formats:
    valid:
    - image/jpeg
    - image/png
    - image/tiff
    - image/jp2
    default: image/jpeg
fedora_resource:
  base_url: http://localhost:8080/fcrepo/rest
log:
  level: DEBUG
  file: "/var/log/crayfish/houdini.log"
syn:
  enable: true
  config: "/opt/www/crayfish/syn-settings.xml"
