---
- name: Restart kubelite
  service:
    name: snap.microk8s.daemon-kubelite
    state: restarted
  become: true
  listen:
    - 'Secrets encryption updated'
- name: Reencrypt secrets
  shell:
    cmd: '{{ microk8s_path }} kubectl get secrets --all-namespaces -o json | {{ microk8s_path }} kubectl replace -f -'
  become: true
  become_user: '{{ microk8s_user.name }}'
  listen:
    - 'Secrets encryption updated'

- name: Ensure ECR Key is set
  command:
    cmd: /usr/bin/ecr-rotate-key.sh
  become: true
  become_user: '{{ microk8s_user.name }}'
  listen:
    - 'Updated pull secrets'
    - 'AWS credentials updated'
