---
- name: Check if aws cli is already installed.
  stat:
    path: '{{ aws_bin_dir }}/aws'
  register: aws_cli_present

- name: Ensure staging direcory exists.
  file:
    path: '{{ staging_dir }}'
    state: directory
    mode: 0770
  when: not aws_cli_present.stat.exists

- name: Ensure installer is present.
  unarchive:
    src: '{{ aws_cli_download }}'
    remote_src: true
    dest: '{{ staging_dir }}'
  when: not aws_cli_present.stat.exists

- name: Install AWS CLI.
  command:
    cmd: './install --bin-dir {{ aws_bin_dir }} --install-dir {{ aws_install_dir }}'
    chdir: '{{ staging_dir }}/aws'
    creates: '{{ aws_bin_dir }}/aws'
  when: not aws_cli_present.stat.exists
  become: true
