
AWSTemplateFormatVersion: 2010-09-09

Parameters:
  Hostname:
    Type: String

Resources:
  ServiceAccount:
    Type: AWS::IAM::User
    Properties:
      ManagedPolicyArns:
        - !ImportValue EcrReadOnlyPolicy
        - !ImportValue EcrAuthPolicy
      UserName: !Sub ${Hostname}-microk8s
