apiVersion: v1
kind: Service
metadata:
  name: svc-activemq
  labels:
    component: activemq
spec:
  ports:
    - name: http
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: 61613
    - name: openwire
      port: 61616
      protocol: TCP
      targetPort: 61616
  selector:
    component: activemq
