apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: activemq
  name: activemq
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.activemq.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: activemq
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: activemq
    spec:
      containers:
      - image: "{{ .Values.activemq.image.repository }}:{{ .Values.activemq.image.tag }}"
        imagePullPolicy: Always
        name: activemq
        ports: 
        - containerPort: 8161
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{ if .Values.activemq.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.activemq.image.pullSecret}}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}