apiVersion: v1
kind: Service
metadata:
  name: svc-cantaloupe
  labels:
    component: cantaloupe
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: cantaloupe
