
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: cantaloupe
  name: cantaloupe
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.cantaloupe.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: cantaloupe
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: cantaloupe
    spec:
      containers:
      - image: "{{ .Values.cantaloupe.image.repository }}:{{ .Values.cantaloupe.image.tag }}"
        imagePullPolicy: Always
        name: cantaloupe
        ports: 
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: cantaloupe-info
          mountPath: /opt/cantaloupe_configs/info.yaml
          subPath: info.yaml
      {{ if .Values.cantaloupe.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.cantaloupe.image.pullSecret}}
      {{- end }}
      volumes:
      - name: cantaloupe-info
        configMap:
          name: cantaloupe-info-{{ .Release.Revision }}
          items:
          - key: info
            path: info.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}