apiVersion: v1
kind: Service
metadata:
  name: svc-clamav
  labels:
    component: clamav
spec:
  ports:
    - name: 3310-clamav
      port: 3310
      protocol: TCP
      targetPort: 3310
  selector:
    component: clamav
