apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: clamav
  name: clamav
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.clamav.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: clamav
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: clamav
    spec:
      containers:
      - image: "{{ .Values.clamav.image.repository }}:{{ .Values.clamav.image.tag }}"
        imagePullPolicy: Always
        name: clamav
        ports:
        - containerPort: 3310
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      {{ if .Values.clamav.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.clamav.image.pullSecret}}
      {{- end }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}