apiVersion: v1
kind: Service
metadata:
  name: svc-db
  labels:
    component: db
spec:
  ports:
    - name: pgsql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    component: db
