apiVersion: v1
kind: Service
metadata:
  name: svc-drupal
  labels:
    component: drupal
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: drupal
