apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: drupal
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: svc-drupal
            port:
              name: http
