apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-islandora-data-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
        component: drupal
        usage: islandora-data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
