apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: drupal-public-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
        component: drupal
        usage: public-filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
