apiVersion: batch/v1
kind: CronJob
metadata:
  name: drupal-rest-oai-pmh
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        metadata:
          name: drupal-rest-oai-pmh
          labels:
            app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
            app.kubernetes.io/instance: {{ .Release.Name | quote }}
            helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
        spec:
          restartPolicy: Never
          containers:
          - name: install-drupal
            image: "{{ .Values.drupal.image.repository }}:{{ .Values.drupal.image.tag }}"
            command:
                - '/bin/bash'
                - '-c'
                - |
                    sudo -Eu www-data drush --uri=http://{{ .Values.ingress.host }}:{{ template "islandora.ingressPort" . }} --debug php:eval "rest_oai_pmh_rebuild_entries()"
            env:
{{ include "islandora.drupalEnv" . | indent 12 }}
            envFrom:
            - configMapRef:
                name: drupal-env
            volumeMounts:
{{ include "islandora.drupalVolumeMounts" . | indent 12 }}
          {{ if .Values.drupal.image.pullSecret -}}
          imagePullSecrets:
          - name: {{ .Values.drupal.image.pullSecret}}
          {{- end }}
          volumes:
{{ include "islandora.drupalVolumes" . | indent 10 }}
