apiVersion: apps/v1
kind:  Deployment
metadata:
  labels:
    component: drupal
  name: drupal
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.drupal.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: drupal
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: drupal
    spec:
      containers:
      - image: "{{ .Values.drupal.image.repository }}:{{ .Values.drupal.image.tag }}"
        imagePullPolicy: Always
        name: drupal
        ports: 
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
{{ include "islandora.drupalEnv" . | indent 8 }}
        envFrom:
        - configMapRef:
            name: drupal-env
        volumeMounts:
{{ include "islandora.drupalVolumeMounts" . | indent 8 }}
      {{ if .Values.drupal.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.drupal.image.pullSecret}}
      {{- end }}
      volumes:
{{ include "islandora.drupalVolumes" . | indent 6 }}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
