{{- if and .Values.init.installSite }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-install-drupal"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-install-drupal"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: install-drupal
        image: "{{ .Values.drupal.image.repository }}:{{ .Values.drupal.image.tag }}"
        command:
            - '/bin/bash'
            - '-c'
            - |
                sudo -Eu www-data drush site-install \
                    dgi_standard_profile \
                    --db-url=pgsql://$DRUPAL_DB_USER:$DRUPAL_DB_PASSWORD@$POSTGRES_HOST:5432/$DRUPAL_DB_NAME \
                    --site-name=default_site \
                    --account-name=$DRUPAL_USER \
                    --account-pass=$DRUPAL_USER_PASS \
                    --account-mail=$DRUPAL_SITE_EMAIL \
                    --sites-subdir=default \
                    --existing-config \
                    -y
                sudo -Eu www-data drush content-sync:import provisioned_content --actions=create --user=1 -y
                sudo -Eu www-data drush content-sync:import i8-specific --actions=create --user=1 -y
                sudo -Eu www-data drush -y migrate:import --userid=1 --group=islandora
                sudo -Eu www-data drush -y state-set dgi_i8_helper_iiif_site_id drupal_d8_default
        env:
{{ include "islandora.drupalEnv" . | indent 8 }}
        - name: DRUPAL_USER
          value: islandora
        - name: DRUPAL_USER_PASS
          value: islandora
        - name: DRUPAL_SITE_EMAIL
          value: noreplysys@discoverygarden.ca
        envFrom:
        - configMapRef:
            name: drupal-env
        volumeMounts:
{{ include "islandora.drupalVolumeMounts" . | indent 8 }}
      {{ if .Values.drupal.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.drupal.image.pullSecret}}
      {{- end }}
      volumes:
{{ include "islandora.drupalVolumes" . | indent 6 }}
{{- end }}
