apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data-claim
spec:
  storageClassName: manual
  selector:
    matchLabels:
        component: postgres
        usage: data
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
