---

apiVersion: v1
kind: Service
metadata:
  name: svc-activemq
  labels:
    component: activemq
spec:
  ports:
    - name: http
      port: 8161
      protocol: TCP
      targetPort: 8161
    - name: stomp
      port: 61613
      protocol: TCP
      targetPort: 61613
    - name: openwire
      port: 61616
      protocol: TCP
      targetPort: 61616
  selector:
    component: activemq

---

apiVersion: v1
kind: Service
metadata:
  name: svc-alpaca
  labels:
    component: alpaca
spec:
  ports:
    - name: 11213-alpaca
      port: 11213
      protocol: TCP
      targetPort: 11213
  selector:
    component: alpaca

---
apiVersion: v1
kind: Service
metadata:
  name: svc-memcache
  labels:
    component: memcache
spec:
  ports:
    - name: 11211-memcache
      port: 11211
      protocol: TCP
      targetPort: 11211
  selector:
    component: memcache

---

apiVersion: v1
kind: Service
metadata:
  name: svc-crayfish
  labels:
    component: crayfish
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: crayfish
---

apiVersion: v1
kind: Service
metadata:
  name: svc-solr
  labels:
    component: solr
spec:
  ports:
    - name: solr
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    component: solr

---

apiVersion: v1
kind: Service
metadata:
  name: svc-cantaloupe
  labels:
    component: cantaloupe
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    component: cantaloupe
---

apiVersion: v1
kind: Service
metadata:
  name: svc-drupal
  labels:
    component: drupal
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 80
  selector:
    component: drupal
---

---
apiVersion: v1
kind: Service
metadata:
  name: svc-db
  labels:
    component: db
spec:
  ports:
    - name: pgsql
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    component: db

---
apiVersion: v1
kind: Service
metadata:
  name: svc-clamav
  labels:
    component: clamav
spec:
  ports:
    - name: 3310-clamav
      port: 3310
      protocol: TCP
      targetPort: 3310
  selector:
    component: clamav
