{{- if (and .Values.init.setup_volumes.permissions  ( eq .Values.storage.type "hostPath" ) ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-setup-solr-volumes"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-setup-solr-volumes"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: "{{ .Release.Name }}-setup-solr-volumes"
        image: busybox
        command: ['chown', '-R', '100:101', '/var/solr/data/islandora8/data']
        volumeMounts:
        - name: data
          mountPath: /var/solr/data/islandora8/data
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: solr-data-claim
{{- end }}
