{{- if (and .Values.init.setup_volumes.permissions  ( eq .Values.storage.type "hostPath" ) ) }}
apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-setup-drupal-volumes"
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  annotations:
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-2"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ .Release.Name }}-install-drupal"
      labels:
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    spec:
      restartPolicy: Never
      containers:
      - name: install-drupal
        image: "{{ .Values.drupal.image.repository }}:{{ .Values.drupal.image.tag }}"
        command:
            - '/bin/bash'
            - '-c'
            - |
                chown -R www-data:www-data /opt/www/drupal/web/sites/default/files
                chown -R www-data:www-data /opt/drupal_private_filesystem/d8/default
                chown -R www-data:www-data /opt/islandora_data
        env:
{{ include "islandora.drupalEnv" . | indent 8 }}
        envFrom:
        - configMapRef:
            name: drupal-env
        volumeMounts:
{{ include "islandora.drupalVolumeMounts" . | indent 8 }}
      {{ if .Values.drupal.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.drupal.image.pullSecret}}
      {{- end }}
      volumes:
{{ include "islandora.drupalVolumes" . | indent 6 }}
{{- end }}
