apiVersion: v1
kind: Service
metadata:
  name: svc-solr
  labels:
    component: solr
spec:
  ports:
    - name: solr
      port: 8983
      protocol: TCP
      targetPort: 8983
  selector:
    component: solr
