apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    component: solr
  name: solr
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: {{ .Values.solr.replicas }}
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      component: solr
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        component: solr
    spec:
      containers:
      - image: "{{ .Values.solr.image.repository }}:{{ .Values.solr.image.tag }}"
        imagePullPolicy: Always
        name: solr
        ports: 
        - containerPort: 8983
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: data
          mountPath: /var/solr/data/islandora8/data
      {{ if .Values.solr.image.pullSecret -}}
      imagePullSecrets:
       - name: {{ .Values.solr.image.pullSecret}}
      {{- end }}
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: solr-data-claim
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
