{{- if eq .Values.storage.type "hostPath" }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: solr-data
  labels:
    component: solr
    usage: data
spec:
  storageClassName: manual
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.storage.basePath }}/{{ .Release.Name }}/solr
    type: DirectoryOrCreate
{{- end}}