networks:
  static-network:
    ipam:
      config:
      - subnet: 172.20.0.0/16
services:
  activemq:
    image: activemq:5.16.2-alpine
    networks:
      static-network:
        ipv4_address: 172.20.100.10
    ports:
      - 8161:8161
  memcached:
    image: memcached:1.6-alpine
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      static-network:
        ipv4_address: 172.20.100.20
  drupal:
    image: drupal-crayfish:8.x-manage
    secrets:
      - db-password
      - crayfish.key
    environment:
    - APACHE_RUN_DIR=/var/www/html
    - APACHE_RUN_USER=www-data
    - APACHE_RUN_GROUP=www-data
    - APACHE_PID_FILE=/var/run/apache2/apache2.pid
    - APACHE_RUN_DIR=/var/run/apache2
    - APACHE_LOCK_DIR=/var/lock/apache2
    - APACHE_LOG_DIR=/var/log/apache2
    - LANG=C
    - POSTGRES_HOST=db
    - DRUPAL_DB_NAME=drupal
    - DRUPAL_DB_USER=drupal
    - DRUPAL_DB_PASSWORD=/run/secrets/db-password
    volumes:
    - ${PWD}/actual.25-80-dgi.conf:/etc/apache2/sites-available/25-80-dgi.conf
    - ${PWD}/actual.settings.php:/opt/www/drupal/sites/default/settings.php
    - ${PWD}/actual.flysystem_config.json:/opt/www/drupal/sites/default/flysystem_config.json
    - ${PWD}/actual.trusted_hosts.json:/opt/www/drupal/sites/default/trusted_hosts.json
    - ${PWD}/actual.islandora_iiif.settings.yml:/opt/www/drupal/sites/default/config_override/islandora_iiif.settings.yml
    - ${PWD}/actual.openseadragon.settings.yml:/opt/www/drupal/sites/default/config_override/openseadragon.settings.yml
    - ${PWD}/actual.search_api.server.default_solr_server.yml:/opt/www/drupal/sites/default/config_override/search_api.server.default_solr_server.yml
    - ${PWD}/actual.clamav.settings.yml:/opt/www/drupal/sites/default/config_override/clamav.settings.yml
    - ${PWD}/actual.islandora.settings.yml:/opt/www/drupal/sites/default/config_override/islandora.settings.yml
    - ${PWD}/actual.key.key.default.yml:/opt/www/drupal/sites/default/config_override/key.key.default.yml
    ports:
    - 80:80
    - 443:443
    networks:
      static-network:
        ipv4_address: 172.20.100.30
  crayfish:
    image: crayfish:3.x
    secrets:
      - crayfish.pub
    networks:
      static-network:
        ipv4_address: 172.20.100.35
  karaf:
    image: karaf:4.2.11-alpine
    volumes:
    - ${PWD}/actual.org.fcrepo.camel.service.activemq.cfg:/opt/karaf/etc/org.fcrepo.camel.service.activemq.cfg
    - ${PWD}/actual.crayfish.dgi.xml:/opt/karaf/deploy/crayfish.dgi.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.homarus.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.homarus.blueprint.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.houdini.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.houdini.blueprint.xml
    - ${PWD}/actual.ca.islandora.alpaca.connector.hypercube.blueprint.xml:/opt/karaf/deploy/ca.islandora.alpaca.connector.hypercube.blueprint.xml
    networks:
      static-network:
        ipv4_address: 172.20.100.40
  solr:
    image: solr:8.9.0-alpine
    networks:
      static-network:
        ipv4_address: 172.20.100.50
  cantaloupe:
    image: cantaloupe:4.1.9-tomcat
    environment:
    - TOMCAT_MEM="1g"
    volumes:
    - ${PWD}/actual.info.yaml:/opt/cantaloupe_configs/info.yaml
    networks:
      static-network:
        ipv4_address: 172.20.100.60
  db:
    image: postgres:12
    secrets:
      - db-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_USER: drupal
      POSTGRES_DB: drupal
      POSTGRES_INITDB_ARGS: -E UTF-8
    networks:
      static-network:
        ipv4_address: 172.20.100.70
  clamav:
    image: clamav/clamav:latest
    networks:
      static-network:
        ipv4_address: 172.20.100.80
secrets:
  db-password:
    file: db/password.txt
  crayfish.key:
    file: keys/default.key
  crayfish.pub:
    file: keys/default.pub
