networks:
  static-network:
    ipam:
      config:
      - subnet: 172.20.0.0/16
services:
  activemq:
    image: activemq:5.16.2-alpine
    networks:
      static-network:
        ipv4_address: 172.20.100.10
    ports:
      - 8161:8161
  memcached:
    image: memcached:1.6-alpine
    deploy:
      resources:
        limits:
          memory: 256M
    networks:
      static-network:
        ipv4_address: 172.20.100.20
  drupal:
    image: drupal:9.x-manage
    secrets:
      - db-password
      - crayfish.key
    environment:
    - LANG=C
    - POSTGRES_HOST=db
    - DRUPAL_DB_NAME=drupal
    - DRUPAL_DB_USER=drupal
    - DRUPAL_DB_PASSWORD_FILE=/run/secrets/db-password
    volumes:
      - ${PWD}/actual.flysystem_config.json:/opt/www/drupal/web/sites/default/flysystem_config.json
      - ${PWD}/actual.trusted_hosts.json:/opt/www/drupal/web/sites/default/trusted_hosts.json
      - ${PWD}/actual.openseadragon.settings.yml:/opt/www/drupal/web/sites/default/config_override/openseadragon.settings.yml
      - ${PWD}/actual.search_api.server.default_solr_server.yml:/opt/www/drupal/web/sites/default/config_override/search_api.server.default_solr_server.yml
      - ${PWD}/actual.key.key.default.yml:/opt/www/drupal/web/sites/default/config_override/key.key.default.yml
    ports:
    - 80:80
    - 443:443
    networks:
      static-network:
        ipv4_address: 172.20.100.30
  crayfish:
    image: crayfish:3.x
    secrets:
      - crayfish.pub
    networks:
      static-network:
        ipv4_address: 172.20.100.35
  alpaca:
    image: alpaca:2.2.0
    networks:
      static-network:
        ipv4_address: 172.20.100.40
  solr:
    image: solr:8.9.0-alpine
    networks:
      static-network:
        ipv4_address: 172.20.100.50
  cantaloupe:
    image: cantaloupe:4.1.9-tomcat9.0.69
    environment:
    - TOMCAT_MEM="1g"
    networks:
      static-network:
        ipv4_address: 172.20.100.60
  db:
    image: postgres:12
    secrets:
      - db-password
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
      POSTGRES_USER: drupal
      POSTGRES_DB: drupal
      POSTGRES_INITDB_ARGS: -E UTF-8
    networks:
      static-network:
        ipv4_address: 172.20.100.70
  clamav:
    image: clamav/clamav:latest
    networks:
      static-network:
        ipv4_address: 172.20.100.80
secrets:
  db-password:
    file: db/password.txt
  crayfish.key:
    file: keys/default.key
  crayfish.pub:
    file: keys/default.pub
